---
- name: Manage groups.
  group:
    name: "{{ item.name }}"
    gid: "{{ item.gid | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    system: "{{ item.system | default(omit) }}"
  with_items: "{{ users_group_list }}"
  when: users_group_list is defined

- name: Manage users.
  user:
    name: "{{ item.username }}"
    append: "{{ item.append | default(true if item.groups is defined else omit) }}"
    comment: "{{ item.comment | default(omit) }}"
    create_home: "{{ item.create_home | default(true) }}"
    home: "{{ item.home | default('/home/' + item.username) }}"
    generate_ssh_key: "{{ item.generate_ssh_key | default(omit) }}"
    # Primary group
    group: "{{ item.group | default(item.username if users_create_group_per_user else users_default_group) }}"
    # Additional groups
    groups: "{{ item.groups | default(omit) }}"
    password: "{{ item.password | password_hash('sha512') if item.password is defined else '!' }}"
    update_password: "{{ item.update_password | default('on_create') }}"
    shell: "{{ item.shell | default(users_default_shell) }}"
    uid: "{{ item.uid | default(omit) }}"
    system: "{{ item.system | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    expires: "{{ item.expires | default(omit) }}"
    force: "{{ item.force | default(omit) }}"
  with_items: "{{ users_user_list }}"
  when: users_user_list is defined
  no_log: true
  register: user_reg

- name: Configure sudoers.
  template:
    src: etc/sudoers.d/sudo-config.j2
    dest: "/etc/sudoers.d/{{ item.username }}"
    mode: "0644"
  with_items: "{{ users_user_list }}"
  when: item.sudo_opts is defined
